domain: audreyeiley.github.io
url: https://audreyeiley.github.io/
baseurl: ""

title: Eiley
email: eileywoo.yiss@gmail.com
author: Eiley

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  email: "eileywoo.yiss@gmail.com"
  # telegram: "https://t.me/"
  # discord: "https://discord.com/"
